spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # manual routes
      routes:
        - id: microA-route
          uri: lb://MICROA
          predicates:
            - Path=/a/**

        - id: microB-route
          uri: lb://MICROB
          predicates:
            - Path=/b/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

tracing:
  sampling:
    probability: 1.0

zipkin:
  tracing:
    endpoint: http://localhost:9412/api/v2/spans
