spring:
  application:
    name: microA
 


# ===============================
# ACTUATOR CONFIG
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

# ===============================
# RESILIENCE4J CONFIG
# ===============================
resilience4j:
  circuitbreaker:
    instances:
      serviceA:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
